feat: add global theme switching config
halo-sigs/plugin-shiki pull request #2
Opened 2024-11-23 03:54 UTC by Aziteee

去除原先的代码块单独配置主题，添加了全局深浅色主题切换配置功能

![image](https://github.com/user-attachments/assets/ab8a4136-bdbf-4459-8698-19f78f7a4d23)

![image](https://github.com/user-attachments/assets/2c3f2636-cd57-4068-bf63-2d6f692812fb)

2024-12-03 07:34 UTC, LIlGG reviewed
/lgtm

2024-12-04 04:10 UTC, ruibaby requested changes
感谢贡献，功能我测试没有问题，以下是一些改进建议。

2024-12-04 04:10 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +          name: themeLight
可以考虑加上 searchable，支持搜索。

https://docs.halo.run/developer-guide/form-schema#select

2024-12-04 04:10 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +        - $formkit: select
同上

2024-12-04 04:10 UTC, ruibaby commented on theme-lib/src/assets/style.css
> +  padding: 1em;
建议为 shiki 添加内边距，观察到不少主题为 pre 添加了边距样式，建议直接覆盖，否则可能造成 code 和 pre 都有内边距。

2024-12-04 04:10 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +          <<: *theme-options
学习了

2024-12-07 16:13 UTC, Aziteee commented on ui/src/editor/code-block-shiki/shiki-plugin.ts
> +          const configmap = await coreApiClient.configMap.getConfigMap({
`fetchPluginJsonConfig`用不了，报错`Uncaught (in promise) TypeError: i.consoleApiClient.plugin.plugin.fetchPluginJsonConfig is not a function`。这可能是一个bug

2024-12-07 16:35 UTC, Aziteee commented on ui/src/editor/code-block-shiki/shiki-plugin.ts
> +          const configmap = await coreApiClient.configMap.getConfigMap({
我改用`fetchPluginConfig`之后没问题了，但是参考示例写了角色模板后没用，能看看有啥地方出问题了吗

```yaml
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-shiki
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-role-template-view-posts: "true"
    rbac.authorization.halo.run/aggregate-to-role-template-post-contributor: "true"
  annotations:
    rbac.authorization.halo.run/module: "Shiki"
    rbac.authorization.halo.run/display-name: "Shiki"
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ "shiki-configmap" ]
    verbs: [ "get" ]
```

2024-12-08 05:54 UTC, ruibaby commented on ui/src/editor/code-block-shiki/shiki-plugin.ts
> +          const configmap = await coreApiClient.configMap.getConfigMap({
> `fetchPluginJsonConfig`用不了，报错`Uncaught (in promise) TypeError: i.consoleApiClient.plugin.plugin.fetchPluginJsonConfig is not a function`。这可能是一个bug

提升依赖（plugin.yaml#spec.requires）以及开发环境运行的 Halo 版本，fetchPluginJsonConfig 应该是在 2.20 才有

2024-12-12 16:04 UTC, ruibaby commented on ui/src/editor/code-block-shiki/shiki-plugin.ts
> +          const configmap = await coreApiClient.configMap.getConfigMap({
> 我改用`fetchPluginConfig`之后没问题了，但是参考示例写了角色模板后没用，能看看有啥地方出问题了吗
> 
> ```yaml
> apiVersion: v1alpha1
> kind: Role
> metadata:
>   name: role-template-shiki
>   labels:
>     halo.run/role-template: "true"
>     halo.run/hidden: "true"
>     rbac.authorization.halo.run/aggregate-to-role-template-view-posts: "true"
>     rbac.authorization.halo.run/aggregate-to-role-template-post-contributor: "true"
>   annotations:
>     rbac.authorization.halo.run/module: "Shiki"
>     rbac.authorization.halo.run/display-name: "Shiki"
> rules:
>   - apiGroups: [ "" ]
>     resources: [ "configmaps" ]
>     resourceNames: [ "shiki-configmap" ]
>     verbs: [ "get" ]
> ```

ping @guqing

2025-09-25 15:54 UTC, closed without merging